services:
  caddy:
    build: .
    restart: unless-stopped
    network_mode: host
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config:/etc/caddy
      - ./resources:/var/www
      - /var/lib/infisical-agent/rendered/caddy:/secrets:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
