services:
  kanidm:
    image: docker.io/kanidm/server:1.10.5@sha256:142f7d82b733ce68c6731fbf1258156fe4cb5f43ff3864e23e2126b484f85b9f
    container_name: kanidm
    restart: unless-stopped
    network_mode: host
    user: "982:982"
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    stop_grace_period: 1m
    tmpfs:
      - /tmp:rw,nosuid,nodev,noexec,size=64m
    volumes:
      - ./server.toml:/data/server.toml:ro
      - /var/lib/kanidm/db:/data/db
      - /var/lib/kanidm/backups:/data/backups
      - /var/lib/kanidm/pki:/data/pki:ro
